version: "2.1"

services:
  twilight-element:
    image: alanb128/twilight-element
    privileged: true
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.sysfs: '1'
      io.balena.features.supervisor-api: '1'
    expose:
      - '7575'
